/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dnebinger.subsystem.events.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the RelatedEvent service. Represents a row in the &quot;SUBSYS_RelatedEvent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dnebinger.subsystem.events.model.impl.RelatedEventModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dnebinger.subsystem.events.model.impl.RelatedEventImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RelatedEvent
 * @generated
 */
@ProviderType
public interface RelatedEventModel extends BaseModel<RelatedEvent> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a related event model instance should use the {@link RelatedEvent} interface instead.
	 */

	/**
	 * Returns the primary key of this related event.
	 *
	 * @return the primary key of this related event
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this related event.
	 *
	 * @param primaryKey the primary key of this related event
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the surrogate ID of this related event.
	 *
	 * @return the surrogate ID of this related event
	 */
	public long getSurrogateId();

	/**
	 * Sets the surrogate ID of this related event.
	 *
	 * @param surrogateId the surrogate ID of this related event
	 */
	public void setSurrogateId(long surrogateId);

	/**
	 * Returns the event ID of this related event.
	 *
	 * @return the event ID of this related event
	 */
	public long getEventId();

	/**
	 * Sets the event ID of this related event.
	 *
	 * @param eventId the event ID of this related event
	 */
	public void setEventId(long eventId);

	/**
	 * Returns the related event ID of this related event.
	 *
	 * @return the related event ID of this related event
	 */
	public long getRelatedEventId();

	/**
	 * Sets the related event ID of this related event.
	 *
	 * @param relatedEventId the related event ID of this related event
	 */
	public void setRelatedEventId(long relatedEventId);

}